/* =============================================
   PDF Export Module — APEX Southern Cross Design
   Uses jsPDF + AutoTable (loaded via CDN)
   ============================================= */

const PDFExport = (() => {
    const { jsPDF } = window.jspdf || {};

    // ─── Brand Colors ───
    const BRAND = {
        primary:   [30, 58, 138],   // #1e3a8a — dark navy
        accent:    [79, 70, 229],   // #4F46E5 — indigo
        success:   [5, 150, 105],   // #059669
        danger:    [220, 38, 38],   // #dc2626
        textDark:  [31, 41, 55],    // #1f2937
        textLight: [107, 114, 128], // #6b7280
        bgLight:   [243, 244, 246], // #f3f4f6
        white:     [255, 255, 255],
    };

    // ─── Logo as Base64 (loaded at init) ───
    let logoBase64 = null;

    function loadLogo() {
        return new Promise((resolve) => {
            const img = new Image();
            img.crossOrigin = 'anonymous';
            img.onload = () => {
                const canvas = document.createElement('canvas');
                canvas.width = img.naturalWidth;
                canvas.height = img.naturalHeight;
                const ctx = canvas.getContext('2d');
                ctx.drawImage(img, 0, 0);
                logoBase64 = canvas.toDataURL('image/png');
                resolve(logoBase64);
            };
            img.onerror = () => resolve(null);
            img.src = 'img/apex_logo.png';
        });
    }

    // ─── Shared: Header ───
    function addHeader(doc, toolName) {
        const pageW = doc.internal.pageSize.getWidth();

        // Logo
        if (logoBase64) {
            doc.addImage(logoBase64, 'PNG', 14, 8, 40, 18);
        }

        // Company name
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...BRAND.primary);
        doc.text('APEX Southern Cross Engineering', 58, 16);

        // Tool name
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...BRAND.textLight);
        doc.text(toolName, 58, 22);

        // Date
        const dateStr = new Date().toLocaleDateString('en-AU', {
            day: '2-digit', month: '2-digit', year: 'numeric',
            hour: '2-digit', minute: '2-digit'
        });
        doc.setFontSize(8);
        doc.text(`Generated: ${dateStr}`, pageW - 14, 16, { align: 'right' });

        // Separator line
        doc.setDrawColor(...BRAND.accent);
        doc.setLineWidth(0.5);
        doc.line(14, 30, pageW - 14, 30);

        return 34; // Y position after header
    }

    // ─── Shared: Footer ───
    function addFooter(doc) {
        const pageW = doc.internal.pageSize.getWidth();
        const pageH = doc.internal.pageSize.getHeight();
        const pageCount = doc.internal.getNumberOfPages();

        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(7);
            doc.setTextColor(...BRAND.textLight);

            // Left: branding
            doc.text('Generated by APEX Southern Cross Design', 14, pageH - 8);

            // Right: page number
            doc.text(`Page ${i} / ${pageCount}`, pageW - 14, pageH - 8, { align: 'right' });

            // Top separator for footer
            doc.setDrawColor(220, 220, 220);
            doc.setLineWidth(0.3);
            doc.line(14, pageH - 14, pageW - 14, pageH - 14);
        }
    }

    // ─── Shared: Section Title ───
    function addSectionTitle(doc, y, title) {
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...BRAND.primary);
        doc.text(title, 14, y);
        return y + 6;
    }

    // ─── Shared: Key-Value Table ───
    function addKeyValueTable(doc, y, data, options = {}) {
        doc.autoTable({
            startY: y,
            head: options.head || [['Parameter', 'Value', 'Unit']],
            body: data,
            theme: 'grid',
            margin: { left: 14, right: 14 },
            styles: {
                fontSize: 9,
                cellPadding: 3,
                lineColor: [220, 220, 220],
                lineWidth: 0.3,
            },
            headStyles: {
                fillColor: BRAND.primary,
                textColor: BRAND.white,
                fontStyle: 'bold',
                fontSize: 9,
            },
            alternateRowStyles: {
                fillColor: [248, 250, 252],
            },
            columnStyles: options.columnStyles || {
                0: { cellWidth: 'auto', fontStyle: 'bold' },
                1: { halign: 'right', textColor: BRAND.accent },
                2: { cellWidth: 30, textColor: BRAND.textLight, fontSize: 8 },
            },
            ...options.tableOptions,
        });
        return doc.lastAutoTable.finalY + 6;
    }

    // ─── Shared: Status Box ───
    function addStatusBox(doc, y, status, label) {
        const pageW = doc.internal.pageSize.getWidth();
        const boxW = pageW - 28;
        const isOK = status.toLowerCase().includes('ok') || status.toLowerCase().includes('pass') || status.toLowerCase().includes('adequate');
        const color = isOK ? BRAND.success : BRAND.danger;

        doc.setFillColor(...color);
        doc.roundedRect(14, y, boxW, 18, 3, 3, 'F');

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...BRAND.white);
        doc.text(status, pageW / 2, y + 8, { align: 'center' });

        if (label) {
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            doc.text(label, pageW / 2, y + 14, { align: 'center' });
        }

        return y + 24;
    }

    // ─── Shared: Total Box ───
    function addTotalBox(doc, y, value, unit) {
        const pageW = doc.internal.pageSize.getWidth();
        const boxW = pageW - 28;

        doc.setFillColor(238, 242, 255); // EEF2FF
        doc.setDrawColor(...BRAND.accent);
        doc.setLineWidth(0.5);
        doc.roundedRect(14, y, boxW, 22, 3, 3, 'FD');

        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...BRAND.accent);
        doc.text(value, pageW / 2, y + 10, { align: 'center' });

        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...BRAND.textLight);
        doc.text(unit, pageW / 2, y + 18, { align: 'center' });

        return y + 28;
    }

    // ─── Helper: Read input value from DOM ───
    function val(id) {
        const el = document.getElementById(id);
        if (!el) return '';
        return el.value || el.textContent || '';
    }

    function num(id, decimals = 2) {
        const v = parseFloat(val(id));
        return isNaN(v) ? '0' : v.toFixed(decimals);
    }

    // ════════════════════════════════════════════
    //   1. PT Spacing & Rate
    // ════════════════════════════════════════════
    function exportPTSpacingRate() {
        const doc = new jsPDF();
        let y = addHeader(doc, 'PT Spacing & Rate Calculator');

        // General Properties
        y = addSectionTitle(doc, y, 'General Properties');
        y = addKeyValueTable(doc, y, [
            ['Number of Strand', num('pt-num-strands', 0), ''],
            ['Diameter', num('pt-diameter', 1), 'mm'],
            ['Area', num('pt-area', 0), 'mm²'],
        ]);

        // X-Direction
        y = addSectionTitle(doc, y, 'X-Direction');
        y = addKeyValueTable(doc, y, [
            ['Fmax', num('pt-fmax-x', 0), 'kN'],
            ['Mass', num('pt-mass-x', 3), 'kg/m'],
            ['Slab Depth', num('pt-depth-x', 0), 'mm'],
            ['PT Spacing', num('pt-spacing-x', 0), 'mm'],
            ['P/A Ratio', getResultText('pt-pa-x'), 'N/mm²'],
            ['PT Rate', getResultText('pt-rate-x'), 'kg/m²'],
        ]);

        // Y-Direction
        y = addSectionTitle(doc, y, 'Y-Direction');
        y = addKeyValueTable(doc, y, [
            ['Fmax', num('pt-fmax-y', 0), 'kN'],
            ['Mass', num('pt-mass-y', 3), 'kg/m'],
            ['Slab Depth', num('pt-depth-y', 0), 'mm'],
            ['PT Spacing', num('pt-spacing-y', 0), 'mm'],
            ['P/A Ratio', getResultText('pt-pa-y'), 'N/mm²'],
            ['PT Rate', getResultText('pt-rate-y'), 'kg/m²'],
        ]);

        // Total
        const total = document.getElementById('pt-total-rate');
        y = addSectionTitle(doc, y, 'Total PT Rate');
        y = addTotalBox(doc, y, total ? total.textContent : '0.00', 'Kilograms per Square Meter (kg/m²)');

        addFooter(doc);
        doc.save('PT_Spacing_Rate.pdf');
    }

    // ════════════════════════════════════════════
    //   2. Punching Shear Check
    // ════════════════════════════════════════════

    // SVG → Base64 image converter
    function svgToImage(svgString, width, height) {
        return new Promise((resolve) => {
            const canvas = document.createElement('canvas');
            canvas.width = width * 2;  // 2x for retina
            canvas.height = height * 2;
            const ctx = canvas.getContext('2d');
            ctx.scale(2, 2);

            const img = new Image();
            const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
            const url = URL.createObjectURL(blob);

            img.onload = () => {
                ctx.fillStyle = '#f8f9fc';
                ctx.fillRect(0, 0, width, height);
                ctx.drawImage(img, 0, 0, width, height);
                URL.revokeObjectURL(url);
                resolve(canvas.toDataURL('image/png'));
            };
            img.onerror = () => {
                URL.revokeObjectURL(url);
                resolve(null);
            };
            img.src = url;
        });
    }

    // Generate PS SVG for a given type
    function getPSDiagramSVG(type) {
        const defs = `
            <defs>
                <marker id="pdf-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                    <path d="M 0 0 L 10 5 L 0 10 z" fill="#374151" />
                </marker>
            </defs>
        `;
        if (type === 'internal') {
            return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 220" width="300" height="220">
                ${defs}
                <rect x="0" y="0" width="300" height="220" fill="#f8f9fc" />
                <rect x="110" y="70" width="80" height="80" fill="#f97316" stroke="#000" stroke-width="1.5"/>
                <text x="200" y="115" font-size="13" font-weight="bold" fill="#374151">X</text>
                <text x="150" y="60" font-size="13" font-weight="bold" fill="#374151">Y</text>
                <rect x="70" y="30" width="160" height="160" rx="20" fill="none" stroke="#4F46E5" stroke-width="2" stroke-dasharray="6,4"/>
                <line x1="50" y1="110" x2="250" y2="110" stroke="#374151" stroke-width="2" marker-end="url(#pdf-arrow)"/>
                <text x="260" y="115" font-weight="bold" font-size="14" fill="#374151">Mx</text>
                <line x1="150" y1="190" x2="150" y2="30" stroke="#374151" stroke-width="2" marker-end="url(#pdf-arrow)"/>
                <text x="140" y="25" font-weight="bold" font-size="14" fill="#374151">My</text>
                <line x1="70" y1="205" x2="230" y2="205" stroke="#6b7280" stroke-width="1.5" marker-start="url(#pdf-arrow)" marker-end="url(#pdf-arrow)"/>
                <text x="150" y="200" text-anchor="middle" font-size="13" fill="#6b7280">ax</text>
                <line x1="50" y1="30" x2="50" y2="190" stroke="#6b7280" stroke-width="1.5" marker-start="url(#pdf-arrow)" marker-end="url(#pdf-arrow)"/>
                <text x="45" y="115" text-anchor="end" font-size="13" fill="#6b7280">ay</text>
            </svg>`;
        } else if (type === 'edge') {
            return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 220" width="300" height="220">
                ${defs}
                <rect x="0" y="50" width="300" height="170" fill="#f8f9fc" />
                <line x1="0" y1="50" x2="300" y2="50" stroke="#000" stroke-width="3"/>
                <rect x="110" y="50" width="80" height="80" fill="#f97316" stroke="#000" stroke-width="1.5"/>
                <text x="200" y="95" font-size="13" font-weight="bold" fill="#374151">X</text>
                <text x="150" y="40" font-size="13" font-weight="bold" fill="#374151">Y</text>
                <path d="M 70 50 L 70 130 Q 70 170 110 170 L 190 170 Q 230 170 230 130 L 230 50" fill="none" stroke="#4F46E5" stroke-width="2" stroke-dasharray="6,4"/>
                <line x1="50" y1="110" x2="250" y2="110" stroke="#374151" stroke-width="2" marker-end="url(#pdf-arrow)"/>
                <text x="260" y="115" font-weight="bold" font-size="14" fill="#374151">Mx</text>
                <line x1="150" y1="190" x2="150" y2="60" stroke="#374151" stroke-width="2" marker-end="url(#pdf-arrow)"/>
                <text x="140" y="55" font-weight="bold" font-size="14" fill="#374151">My</text>
                <line x1="70" y1="190" x2="230" y2="190" stroke="#6b7280" stroke-width="1.5" marker-start="url(#pdf-arrow)" marker-end="url(#pdf-arrow)"/>
                <text x="150" y="185" text-anchor="middle" font-size="13" fill="#6b7280">ax</text>
                <line x1="50" y1="50" x2="50" y2="170" stroke="#6b7280" stroke-width="1.5" marker-start="url(#pdf-arrow)" marker-end="url(#pdf-arrow)"/>
                <text x="45" y="115" text-anchor="end" font-size="13" fill="#6b7280">ay</text>
            </svg>`;
        } else {
            return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 220" width="300" height="220">
                ${defs}
                <rect x="0" y="50" width="240" height="170" fill="#f8f9fc" />
                <polyline points="0,50 240,50 240,220" fill="none" stroke="#000" stroke-width="3"/>
                <rect x="140" y="50" width="100" height="80" fill="#f97316" stroke="#000" stroke-width="1.5"/>
                <text x="250" y="95" font-size="13" font-weight="bold" fill="#374151">X</text>
                <text x="190" y="40" font-size="13" font-weight="bold" fill="#374151">Y</text>
                <path d="M 100 50 L 100 130 Q 100 170 140 170 L 240 170" fill="none" stroke="#4F46E5" stroke-width="2" stroke-dasharray="6,4"/>
                <line x1="50" y1="110" x2="210" y2="110" stroke="#374151" stroke-width="2" marker-end="url(#pdf-arrow)"/>
                <text x="220" y="115" font-weight="bold" font-size="14" fill="#374151">Mx</text>
                <line x1="190" y1="190" x2="190" y2="70" stroke="#374151" stroke-width="2" marker-end="url(#pdf-arrow)"/>
                <text x="175" y="65" font-weight="bold" font-size="14" fill="#374151">My</text>
                <line x1="100" y1="190" x2="240" y2="190" stroke="#6b7280" stroke-width="1.5" marker-start="url(#pdf-arrow)" marker-end="url(#pdf-arrow)"/>
                <text x="170" y="185" text-anchor="middle" font-size="13" fill="#6b7280">ax</text>
                <line x1="70" y1="50" x2="70" y2="170" stroke="#6b7280" stroke-width="1.5" marker-start="url(#pdf-arrow)" marker-end="url(#pdf-arrow)"/>
                <text x="65" y="110" text-anchor="end" font-size="13" fill="#6b7280">ay</text>
            </svg>`;
        }
    }

    // Calculate PS for a given type (pure math, no DOM writes)
    function calcPSForType(type) {
        const dimX = parseFloat(val('ps-dim-x')) || 0;
        const dimY = parseFloat(val('ps-dim-y')) || 0;
        const depth = parseFloat(val('ps-depth')) || 0;
        const cover = parseFloat(val('ps-cover')) || 0;
        const fc = parseFloat(val('ps-fc')) || 0;
        const fcp = parseFloat(val('ps-fcp')) || 0;
        const reduction = Math.abs(parseFloat(val('ps-reduction')) || 0);
        const v = parseFloat(val('ps-v')) || 0;
        const mx = parseFloat(val('ps-mx')) || 0;
        const my = parseFloat(val('ps-my')) || 0;
        const bar3 = parseFloat(val('ps-bar-3')) || 0;
        const bar4 = parseFloat(val('ps-bar-4')) || 0;

        const do_eff = depth - cover - Math.max(bar3, bar4);
        let u = 0, ax = 0, ay = 0;

        if (type === 'internal') {
            u = 2 * (dimX + dimY) + Math.PI * do_eff;
            ax = dimX + do_eff;
            ay = dimY + do_eff;
        } else if (type === 'edge') {
            u = 2 * dimX + dimY + (Math.PI / 2) * do_eff;
            ax = dimX + do_eff;
            ay = dimY + do_eff / 2;
        } else {
            u = dimX + dimY + (Math.PI / 4) * do_eff;
            ax = dimX + do_eff / 2;
            ay = dimY + do_eff / 2;
        }
        u = Math.max(0, u - reduction);

        const fcv = 0.17 * Math.sqrt(fc) + 0.3 * fcp;
        const phi = 0.75;
        const fVuo = phi * fcv * u * do_eff / 1000;
        const fVumax = 0.2 * fc * u * do_eff / 1000 * phi;

        let m_factor = 1;
        if (v > 0 && do_eff > 0) {
            if (type === 'internal') {
                m_factor = 1 + (u * mx * 1000) / (8 * v * ax * do_eff) + (u * my * 1000) / (8 * v * ay * do_eff);
            } else if (type === 'edge') {
                m_factor = 1 + (u * mx * 1000) / (8 * v * ax * do_eff) + (u * my * 1000) / (2 * v * ay * do_eff);
            } else {
                m_factor = 1 + (u * mx * 1000) / (2 * v * ax * do_eff) + (u * my * 1000) / (2 * v * ay * do_eff);
            }
        }
        if (!isFinite(m_factor) || m_factor < 1) m_factor = 1;
        const fVu = v * m_factor;

        let status = 'OK', statusDesc = 'No shear reinforcement required';
        if (fVu > fVumax) { status = 'FAIL'; statusDesc = 'Exceeds maximum allowable capacity'; }
        else if (fVu > fVuo) { status = 'REO REQ'; statusDesc = 'Shear reinforcement is required'; }

        return { do_eff, u, fcv, fVu, fVuo, fVumax, status, statusDesc };
    }

    async function exportPunchingShear() {
        const doc = new jsPDF();
        let y = addHeader(doc, 'Punching Shear Check — AS3600');

        // Shared inputs
        y = addSectionTitle(doc, y, 'Geometry & Properties');
        y = addKeyValueTable(doc, y, [
            ['Column X', num('ps-dim-x', 0), 'mm'],
            ['Column Y', num('ps-dim-y', 0), 'mm'],
            ['Slab D', num('ps-depth', 0), 'mm'],
            ['Cover', num('ps-cover', 0), 'mm'],
            ["f'c", num('ps-fc', 0), 'MPa'],
            ['fcp', num('ps-fcp', 1), 'MPa'],
            ['Perim. Reduc.', num('ps-reduction', 0), 'mm'],
        ]);

        y = addSectionTitle(doc, y, 'Loads & Reinforcement');
        y = addKeyValueTable(doc, y, [
            ['V* (kN)', num('ps-v', 0), 'kN'],
            ['M*x (kNm)', num('ps-mx', 0), 'kNm'],
            ['M*y (kNm)', num('ps-my', 0), 'kNm'],
            ['3rd Bar Ø', num('ps-bar-3', 0), 'mm'],
            ['4th Bar Ø', num('ps-bar-4', 0), 'mm'],
        ]);

        // ── 3 Column Types ──
        const types = [
            { id: 'internal', label: 'Internal Column' },
            { id: 'edge',     label: 'Edge Column' },
            { id: 'corner',   label: 'Corner Column' },
        ];

        for (const colType of types) {
            // Check page space — add new page if < 110 remaining
            const pageH = doc.internal.pageSize.getHeight();
            if (y > pageH - 110) {
                doc.addPage();
                y = addHeader(doc, 'Punching Shear Check — AS3600');
            }

            y = addSectionTitle(doc, y, `── ${colType.label} ──`);

            // SVG Diagram
            const svgStr = getPSDiagramSVG(colType.id);
            const imgData = await svgToImage(svgStr, 300, 220);
            if (imgData) {
                const imgW = 65;
                const imgH = imgW * (220 / 300);
                doc.addImage(imgData, 'PNG', 14, y, imgW, imgH);

                // Results table alongside diagram
                const r = calcPSForType(colType.id);
                doc.autoTable({
                    startY: y,
                    margin: { left: 85, right: 14 },
                    head: [['Parameter', 'Value']],
                    body: [
                        ['Effective Depth (do)', `${Math.max(0, r.do_eff).toFixed(0)} mm`],
                        ['Critical Perimeter (u)', `${Math.max(0, r.u).toFixed(0)} mm`],
                        ['Shear Strength (fcv)', `${r.fcv.toFixed(2)} MPa`],
                        ['Design Load (fVu)', `${r.fVu.toFixed(0)} kN`],
                        ['Capacity (fVuo)', `${r.fVuo.toFixed(0)} kN`],
                        ['Max Capacity (fVumax)', `${r.fVumax.toFixed(0)} kN`],
                        ['STATUS', r.status],
                    ],
                    theme: 'grid',
                    styles: { fontSize: 8, cellPadding: 2.5, lineColor: [220, 220, 220], lineWidth: 0.3 },
                    headStyles: { fillColor: BRAND.primary, textColor: BRAND.white, fontStyle: 'bold', fontSize: 8 },
                    columnStyles: {
                        0: { fontStyle: 'bold', cellWidth: 50 },
                        1: { halign: 'right', textColor: BRAND.accent },
                    },
                    didParseCell: function(data) {
                        if (data.section === 'body' && data.row.index === 6) {
                            const text = data.cell.raw || '';
                            if (text === 'FAIL') {
                                data.cell.styles.textColor = [220, 38, 38];
                                data.cell.styles.fillColor = [254, 226, 226];
                                data.cell.styles.fontStyle = 'bold';
                            } else if (text === 'REO REQ') {
                                data.cell.styles.textColor = [217, 119, 6];
                                data.cell.styles.fillColor = [255, 251, 235];
                                data.cell.styles.fontStyle = 'bold';
                            } else if (text === 'OK') {
                                data.cell.styles.textColor = [21, 128, 61];
                                data.cell.styles.fillColor = [220, 252, 231];
                                data.cell.styles.fontStyle = 'bold';
                            }
                            if (data.column.index === 0 && text === 'STATUS') {
                                data.cell.styles.fontStyle = 'bold';
                            }
                        }
                    },
                });
                y = Math.max(y + imgH, doc.lastAutoTable.finalY) + 8;
            }
        }

        addFooter(doc);
        doc.save('Punching_Shear_Check.pdf');
    }

    // ════════════════════════════════════════════
    //   3. Strut & Tie Check
    // ════════════════════════════════════════════
    function exportStrutAndTie() {
        const doc = new jsPDF();
        let y = addHeader(doc, 'Strut & Tie Check — AS3600-2018');

        // Input table
        y = addSectionTitle(doc, y, 'Input Parameters');
        const inputData = [];
        document.querySelectorAll('#st-tab-strength .st-input-table tbody tr').forEach(row => {
            if (row.classList.contains('st-section-header')) {
                const td = row.querySelector('td');
                if (td) inputData.push([{ content: td.textContent.trim(), colSpan: 3, styles: { fontStyle: 'bold', fillColor: BRAND.bgLight } }]);
            } else {
                const cells = row.querySelectorAll('td');
                if (cells.length >= 2) {
                    const label = cells[0].textContent.trim();
                    const input = cells[1].querySelector('input, select');
                    const computed = cells[1].querySelector('.st-computed-val') || cells[1];
                    const value = input ? input.value : computed.textContent.trim();
                    const formula = cells[2] ? cells[2].textContent.trim() : '';
                    inputData.push([label, value, formula]);
                }
            }
        });
        if (inputData.length > 0) {
            y = addKeyValueTable(doc, y, inputData, {
                head: [['Parameter', 'Value', 'Formula / Note']],
                columnStyles: {
                    0: { cellWidth: 50, fontStyle: 'bold' },
                    1: { halign: 'right', textColor: BRAND.accent, cellWidth: 30 },
                    2: { textColor: BRAND.textLight, fontSize: 7 },
                }
            });
        }

        // Output table
        y = addSectionTitle(doc, y, 'Output — Calculations');
        const outputData = [];
        document.querySelectorAll('#st-tab-strength .st-output-table tbody tr').forEach(row => {
            if (row.classList.contains('st-section-header')) {
                const td = row.querySelector('td');
                if (td) outputData.push([{ content: td.textContent.trim(), colSpan: 3, styles: { fontStyle: 'bold', fillColor: BRAND.bgLight } }]);
            } else {
                const cells = row.querySelectorAll('td');
                if (cells.length >= 2) {
                    const label = cells[0].textContent.trim();
                    const value = cells[1].textContent.trim();
                    const formula = cells[2] ? cells[2].textContent.trim() : '';
                    outputData.push([label, value, formula]);
                }
            }
        });
        if (outputData.length > 0) {
            y = addKeyValueTable(doc, y, outputData, {
                head: [['Parameter', 'Value', 'Formula']],
                columnStyles: {
                    0: { cellWidth: 50, fontStyle: 'bold' },
                    1: { halign: 'right', textColor: BRAND.accent, cellWidth: 30 },
                    2: { textColor: BRAND.textLight, fontSize: 7 },
                }
            });
        }

        // Status
        const statusEl = document.querySelector('.st-status-value');
        if (statusEl) {
            y = addStatusBox(doc, y, statusEl.textContent.trim(), 'Strut & Tie Verification');
        }

        addFooter(doc);
        doc.save('Strut_And_Tie_Check.pdf');
    }

    // ════════════════════════════════════════════
    //   4. Integrity Reinforcement
    // ════════════════════════════════════════════
    function exportIntegrityReinforcement() {
        const doc = new jsPDF({ orientation: 'landscape' });
        let y = addHeader(doc, 'Integrity Reinforcement — AS3600-2018 Cl 9.2');

        // ── Input & Code Parameters ──
        y = addSectionTitle(doc, y, 'Input & Code Parameters');
        const Fz = val('ir-Fz') || '0';
        const phi = val('ir-phi') || '0';
        const fsy = val('ir-fsy') || '0';
        const AsReq = document.getElementById('ir-res-Asreq');
        const asReqVal = AsReq ? AsReq.textContent.trim() : '0';

        y = addKeyValueTable(doc, y, [
            ['Fz (kN)', Fz, 'reaction'],
            ['φ', phi, 'Cl 9.2'],
            ['fsy (MPa)', fsy, 'yield'],
            ['As,req (mm²)', asReqVal, '= 2×Fz×1000/(φ×fsy)'],
        ], {
            head: [['Parameter', 'Value', 'Note']],
            columnStyles: {
                0: { cellWidth: 45, fontStyle: 'bold' },
                1: { halign: 'right', textColor: BRAND.accent, cellWidth: 30 },
                2: { textColor: BRAND.textLight, fontSize: 8 },
            }
        });

        // ── Column Sections Schedule ──
        y = addSectionTitle(doc, y, 'Column Sections Reinforcement Schedule & Integrity Check');

        const sectionRows = [];
        const tbody = document.getElementById('ir-sections-body');
        if (tbody) {
            tbody.querySelectorAll('tr').forEach(row => {
                const nameInput = row.querySelector('.ir-sec-name');
                const longCount = row.querySelector('.ir-long-count');
                const longDia = row.querySelector('.ir-long-dia');
                const latCount = row.querySelector('.ir-lat-count');
                const latDia = row.querySelector('.ir-lat-dia');

                if (!nameInput) return;

                // Read Set 1-4 values and statuses from badge cells
                const setCells = row.querySelectorAll('td');
                const sets = [];
                // Cells: name(0), long(1), lat(2), set1(3), set2(4), set3(5), set4(6), delete(7)
                for (let i = 3; i <= 6; i++) {
                    if (setCells[i]) {
                        const valSpan = setCells[i].querySelector('span[style*="color:#1e40af"]');
                        const statusSpan = setCells[i].querySelector('span[style*="border-radius"]');
                        const setVal = valSpan ? valSpan.textContent.trim() : '-';
                        const setStatus = statusSpan ? statusSpan.textContent.trim() : '-';
                        sets.push(`${setVal} (${setStatus})`);
                    } else {
                        sets.push('-');
                    }
                }

                sectionRows.push([
                    nameInput.value || '-',
                    `${longCount ? longCount.value : '-'} × N${longDia ? longDia.value : '-'}`,
                    `${latCount ? latCount.value : '-'} × N${latDia ? latDia.value : '-'}`,
                    ...sets,
                ]);
            });
        }

        if (sectionRows.length > 0) {
            doc.autoTable({
                startY: y,
                head: [['Section', 'Longitudinal', 'Latitude', 'Set 1 (4-side)', 'Set 2 (3-long)', 'Set 3 (3-short)', 'Set 4 (2-side)']],
                body: sectionRows,
                theme: 'grid',
                margin: { left: 14, right: 14 },
                styles: {
                    fontSize: 8,
                    cellPadding: 3,
                    lineColor: [220, 220, 220],
                    lineWidth: 0.3,
                    halign: 'center',
                },
                headStyles: {
                    fillColor: BRAND.primary,
                    textColor: BRAND.white,
                    fontStyle: 'bold',
                    fontSize: 8,
                },
                columnStyles: {
                    0: { fontStyle: 'bold', halign: 'left' },
                    1: { halign: 'center' },
                    2: { halign: 'center' },
                },
                didParseCell: function(data) {
                    if (data.section === 'body' && data.column.index >= 3) {
                        const text = data.cell.raw || '';
                        if (text.includes('FAIL')) {
                            data.cell.styles.textColor = [185, 28, 28]; // red
                            data.cell.styles.fillColor = [254, 226, 226]; // red bg
                        } else if (text.includes('OK')) {
                            data.cell.styles.textColor = [21, 128, 61]; // green
                            data.cell.styles.fillColor = [220, 252, 231]; // green bg
                        }
                    }
                },
            });
            y = doc.lastAutoTable.finalY + 8;
        }

        // ── Development Length (Ld) Table ──
        y = addSectionTitle(doc, y, 'Development Length (Ld)');
        const ldData = [
            ['N12', '113', '960', '1000'],
            ['N16', '201', '1280', '1300'],
            ['N20', '314', '1600', '1600'],
            ['N24', '452', '1920', '2000'],
            ['N28', '616', '2240', '2300'],
            ['N32', '804', '2560', '2600'],
            ['N36', '1018', '2880', '2900'],
            ['N40', '1257', '2880', '2900'],
        ];
        doc.autoTable({
            startY: y,
            head: [['Bar', 'Area (mm²)', 'Ld (mm)', 'Ext. (mm)']],
            body: ldData,
            theme: 'grid',
            margin: { left: 14, right: 14 },
            tableWidth: 160,
            styles: {
                fontSize: 8,
                cellPadding: 3,
                lineColor: [220, 220, 220],
                lineWidth: 0.3,
                halign: 'center',
            },
            headStyles: {
                fillColor: [2, 132, 199], // sky blue
                textColor: BRAND.white,
                fontStyle: 'bold',
                fontSize: 8,
            },
            columnStyles: {
                0: { fontStyle: 'bold' },
                3: { textColor: BRAND.accent, fontStyle: 'bold' },
            },
        });

        addFooter(doc);
        doc.save('Integrity_Reinforcement.pdf');
    }

    // ════════════════════════════════════════════
    //   5. Corbel Design
    // ════════════════════════════════════════════
    function exportCorbelDesign() {
        const doc = new jsPDF();
        let y = addHeader(doc, 'Corbel Design — Strut & Tie Model');

        // Input
        y = addSectionTitle(doc, y, 'Input Parameters');
        const inputData = [];
        document.querySelectorAll('.st-input-table tbody tr').forEach(row => {
            if (row.classList.contains('st-section-header')) {
                const td = row.querySelector('td');
                if (td) inputData.push([{ content: td.textContent.trim(), colSpan: 3, styles: { fontStyle: 'bold', fillColor: BRAND.bgLight } }]);
            } else {
                const cells = row.querySelectorAll('td');
                if (cells.length >= 2) {
                    const label = cells[0].textContent.trim();
                    const input = cells[1].querySelector('input, select');
                    const computed = cells[1].querySelector('.st-computed-val') || cells[1];
                    const value = input ? input.value : computed.textContent.trim();
                    const formula = cells[2] ? cells[2].textContent.trim() : '';
                    inputData.push([label, value, formula]);
                }
            }
        });
        if (inputData.length > 0) {
            y = addKeyValueTable(doc, y, inputData, {
                head: [['Parameter', 'Value', 'Note']],
                columnStyles: {
                    0: { cellWidth: 55, fontStyle: 'bold' },
                    1: { halign: 'right', textColor: BRAND.accent, cellWidth: 30 },
                    2: { textColor: BRAND.textLight, fontSize: 7 },
                }
            });
        }

        // Output
        y = addSectionTitle(doc, y, 'Output — Calculations');
        const outputData = [];
        document.querySelectorAll('.st-output-table tbody tr').forEach(row => {
            if (row.classList.contains('st-section-header')) {
                const td = row.querySelector('td');
                if (td) outputData.push([{ content: td.textContent.trim(), colSpan: 3, styles: { fontStyle: 'bold', fillColor: BRAND.bgLight } }]);
            } else {
                const cells = row.querySelectorAll('td');
                if (cells.length >= 2) {
                    const label = cells[0].textContent.trim();
                    const value = cells[1].textContent.trim();
                    const formula = cells[2] ? cells[2].textContent.trim() : '';
                    outputData.push([label, value, formula]);
                }
            }
        });
        if (outputData.length > 0) {
            y = addKeyValueTable(doc, y, outputData, {
                head: [['Parameter', 'Value', 'Formula']],
                columnStyles: {
                    0: { cellWidth: 55, fontStyle: 'bold' },
                    1: { halign: 'right', textColor: BRAND.accent, cellWidth: 30 },
                    2: { textColor: BRAND.textLight, fontSize: 7 },
                }
            });
        }

        // Status
        const statusEl = document.querySelector('.st-status-value');
        if (statusEl) {
            y = addStatusBox(doc, y, statusEl.textContent.trim(), 'Corbel Design Verification');
        }

        addFooter(doc);
        doc.save('Corbel_Design.pdf');
    }

    // ─── Helpers ───
    function getResultText(id) {
        const el = document.getElementById(id);
        if (!el) return '0.00';
        // Remove unit span, keep just the number
        const clone = el.cloneNode(true);
        const unit = clone.querySelector('.calc-result-unit');
        if (unit) unit.remove();
        return clone.textContent.trim();
    }

    function getCleanValue(el) {
        const clone = el.cloneNode(true);
        const unit = clone.querySelector('.calc-result-unit');
        if (unit) unit.remove();
        return clone.textContent.trim();
    }

    // ─── Export Dispatcher ───
    const exportMap = {
        'pt-spacing-rate':          exportPTSpacingRate,
        'punching-shear':           exportPunchingShear,
        'strut-and-tie':            exportStrutAndTie,
        'integrity-reinforcement':  exportIntegrityReinforcement,
        'corbel-design':            exportCorbelDesign,
    };

    async function exportCurrentTool(toolId) {
        if (!window.jspdf) {
            alert('PDF library is loading, please try again in a few seconds.');
            return;
        }
        // Ensure logo is loaded
        if (!logoBase64) await loadLogo();

        const fn = exportMap[toolId];
        if (fn) {
            fn();
        } else {
            alert('PDF export not yet available for this tool.');
        }
    }

    // Pre-load logo
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', loadLogo);
    } else {
        loadLogo();
    }

    return { exportCurrentTool };
})();
